on:
  release:
    types: [published]

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: circle_jump_windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: circle-jump
          ITCH_USER: karvalho
          PACKAGE: circle_jump_windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
  release_web:
    runs-on: ubuntu-latest
    steps:
      - name: download Web
        id: download-web
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: circle_jump_web.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Web)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: circle-jump
          ITCH_USER: karvalho
          PACKAGE: circle_jump_web.zip
          VERSION: ${{ steps.download-web.outputs.version }}
